version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://timelogger_super_user:hcSqOsmGE6XXrAyeFFlNRGVscW7sFzz0@dpg-cu544flds78s73dvdaq0-a.frankfurt-postgres.render.com/timelogger_lj7p
      - FLASK_APP=app.py
      - FLASK_ENV=production
    env_file:
      - .env 