services:
  - type: web
    name: timelogger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://timelogger_super_user:hcSqOsmGE6XXrAyeFFlNRGVscW7sFzz0@dpg-cu544flds78s73dvdaq0-a.frankfurt-postgres.render.com/timelogger_lj7p
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "10000" 